# Generated by Django 4.2.5 on 2023-09-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='My_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name_uz', models.CharField(max_length=200)),
                ('book_name_en', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='About_books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_uz', models.CharField(max_length=255)),
                ('about_en', models.CharField(max_length=255)),
                ('about_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_books.my_books')),
            ],
            options={
                'db_table': 'about',
            },
        ),
    ]
