# Generated by Django 4.2.3 on 2023-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name='name of pupil')),
                ('score', models.IntegerField(verbose_name='ball of pupil')),
            ],
        ),
    ]
