# Generated by Django 4.2.5 on 2023-09-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name_uz', models.CharField(max_length=255, verbose_name='kitobning nomi')),
                ('book_name_en', models.CharField(max_length=255, verbose_name='name of book')),
                ('about_uz', models.CharField(max_length=255, verbose_name='kitob haqida')),
                ('about_en', models.CharField(max_length=255, verbose_name='about book')),
            ],
            options={
                'db_table': 'books',
            },
        ),
    ]
