# Generated by Django 4.2.3 on 2023-09-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name='name of pupil')),
                ('score', models.IntegerField(verbose_name='ball of pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Pupils2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100, verbose_name='name of pupil')),
                ('score', models.IntegerField(verbose_name='ball of pupil')),
            ],
        ),
        migrations.DeleteModel(
            name='Pupils',
        ),
    ]
